{% set name = "sortedcontainers" %}
{% set version = "2.1.0" %}
{% set sha256 = "974e9a32f56b17c1bac2aebd9dcf197f3eb9cd30553c5852a3187ad162e1a03a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - sortedcontainers

about:
  home: http://www.grantjenks.com/docs/sortedcontainers/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Python Sorted Container Types: SortedList, SortedDict, and SortedSet'
  description: |
    SortedContainers is a sorted collections library, written in pure-Python
    and fast as C-extensions.
  doc_url: http://www.grantjenks.com/docs/sortedcontainers/
  dev_url: https://github.com/grantjenks/python-sortedcontainers
  doc_source_url: https://github.com/grantjenks/python-sortedcontainers/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - grantjenks
    - msarahan
    - richafrank
    - nehaljwani
