{% set name = "sortedcontainers" %}
{% set version = "2.2.0" %}
{% set sha256 = "331f5b7acb6bdfaf0b0646f5f86c087e414c9ae9d85e2076ad2eacb17ec2f4ff" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - sortedcontainers

about:
  home: http://www.grantjenks.com/docs/sortedcontainers/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Python Sorted Container Types: SortedList, SortedDict, and SortedSet'
  description: |
    SortedContainers is a sorted collections library, written in pure-Python
    and fast as C-extensions.
  doc_url: http://www.grantjenks.com/docs/sortedcontainers/
  dev_url: https://github.com/grantjenks/python-sortedcontainers
  doc_source_url: https://github.com/grantjenks/python-sortedcontainers/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - grantjenks
    - msarahan
    - richafrank
    - nehaljwani
