{% set name = "sortedcontainers" %}
{% set version = "2.4.0" %}
{% set sha256 = "25caa5a06cc30b6b83d11423433f65d1f9d76c4c6a0c90e3379eaa43b9bfdb88" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - sortedcontainers

about:
  home: http://www.grantjenks.com/docs/sortedcontainers/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Python Sorted Container Types: SortedList, SortedDict, and SortedSet'
  description: |
    SortedContainers is a sorted collections library, written in pure-Python
    and fast as C-extensions.
  doc_url: http://www.grantjenks.com/docs/sortedcontainers/
  dev_url: https://github.com/grantjenks/python-sortedcontainers
  doc_source_url: https://github.com/grantjenks/python-sortedcontainers/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - grantjenks
    - msarahan
    - richafrank
    - nehaljwani
